Bug 4829: IPC shared memory leaks when disker queue overflows
The fixed leak was accompanied by these cache.log errors:

ERROR: worker I/O push queue for ... overflow: ...

I/O queue overflows during disk read requests log the same error but do
not leak memory. Repeated overflows during disk write requests could
eventually exhaust IPC shared memory:

ERROR: ... exception: run out of shared memory pages for IPC I/O

With IPC memory exhausted due to leaks, rock disk I/O stops forever.

Cherry-picked master commit d0c5cf9e.